config/routes.rb
Intensionusa::Application.routes.draw do

  resources :sizes

  resources :metafields do
  	resources :values, :shallow => true
  end

  resources :categories do
 	 resources :sizes, :shallow => true
  end

  resources :materials

  resources :makes
  resources :models do
  	resources :model_products
  end
  get 'makes/:id/models' => 'models#make'

  get 'products' => 'products#index'
  get 'products/:id' => 'products#show'
  post 'products/:id' => 'products#update'

  get 'shopify/product-types' => 'shopify#product_types'
  get 'shopify/:product_type/products' => 'shopify#product_type_products'
  get 'shopify/products' => 'shopify#products'
  get 'shopify/:id/product' => 'shopify#product'
  post 'shopify/:id/product/variant' => 'shopify#product_variant'
  get 'shopify/:product_type/metafields' => 'shopify#metafields'
  get 'shopify/savings-calculator' => 'shopify#savings_calculator'
  get 'shopify/find-your-wheelset' => 'shopify#find_your_wheelset'
  get 'shopify/wheel-customizer' => 'shopify#wheel_customizer'

  root 'pages#index'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :sizes
end

app/models/make.rb
class Make < ActiveRecord::Base
	has_many :models
end

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :models
end

app/models/metafield.rb
class Metafield < ActiveRecord::Base
	has_many :values
end

app/models/model.rb
class Model < ActiveRecord::Base
	belongs_to :make
	belongs_to :model
	has_many :model_products
	def self.filter(params)
		filter = self.scoped
		filter = filter.where(:id => params[:model_id]) if params[:model_id]
		filter = filter.where(:material_id => params[:material_id]) if params[:material_id]
		filter
	end
end

app/models/model_product.rb
class ModelProduct < ActiveRecord::Base
	belongs_to :model
end

app/models/product.rb
class Product < ShopifyAPI::Product
	def self.types()
		self.find(:all).map(&:product_type).uniq
	end
end

app/models/size.rb
class Size < ActiveRecord::Base
	belongs_to :category
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
end

app/models/value.rb
class Value < ActiveRecord::Base
	belongs_to :metafield
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render action: 'show', status: :created, location: @make }
      else
        format.html { render action: 'new' }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:name)
    end
end

app/controllers/metafields_controller.rb
class MetafieldsController < ApplicationController
  before_action :set_metafield, only: [:show, :edit, :update, :destroy]

  # GET /metafields
  # GET /metafields.json
  def index
  	@product_types = Metafield.find(:all).map(&:product_type).uniq
    @metafields = Metafield.all
  end

  # GET /metafields/1
  # GET /metafields/1.json
  def show
  end

  # GET /metafields/new
  def new
    @metafield = Metafield.new
    @product_types = ShopifyAPI.throttle { ShopifyAPI::Product.find(:all).map(&:product_type).uniq }
  end

  # GET /metafields/1/edit
  def edit
    @product_types = ShopifyAPI.throttle { ShopifyAPI::Product.find(:all).map(&:product_type).uniq }
  end

  # POST /metafields
  # POST /metafields.json
  def create
    @metafield = Metafield.new(metafield_params)

    respond_to do |format|
      if @metafield.save
        format.html { redirect_to @metafield, notice: 'Metafield was successfully created.' }
        format.json { render action: 'show', status: :created, location: @metafield }
      else
        format.html { render action: 'new' }
        format.json { render json: @metafield.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metafields/1
  # PATCH/PUT /metafields/1.json
  def update
    respond_to do |format|
      if @metafield.update(metafield_params)
        format.html { redirect_to @metafield, notice: 'Metafield was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @metafield.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metafields/1
  # DELETE /metafields/1.json
  def destroy
    @metafield.destroy
    respond_to do |format|
      format.html { redirect_to metafields_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metafield
      @metafield = Metafield.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metafield_params
      params.require(:metafield).permit(:product_type, :description, :key, :namespace, :value, :value_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/metafields_helper.rb
module MetafieldsHelper
	def format_key(key)
		key.humanize.split.map(&:capitalize).join(' ')
	end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopify_helper.rb
module ShopifyHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/metafields/_form.html.erb
<%= form_for(@metafield) do |f| %>

	<% if @metafield.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@metafield.errors.count, "error") %> prohibited this metafield from being saved:</h2>
			<ul>
			<% @metafield.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :product_type %>
		<%= select(:metafield, :product_type, @product_types, {}, { :class => 'form-control' }) %>
	</div>
	<div class="form-group">
		<%= f.label :key %>
		<%= f.text_field :key, :class => 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_field :description, :maxlength => 255, :class => 'form-control' %>
	</div>
	<%= f.submit 'Add', :class => 'btn btn-success' %>

<% end %>

app/views/metafields/edit.html.erb
<h1>Editing metafield</h1>

<%= render 'form' %>

<%= link_to 'Show', @metafield %> |
<%= link_to 'Back', metafields_path %>

app/views/metafields/index.html.erb
<h1>
	Metafields
	<%= link_to 'Add', new_metafield_path, :class => 'btn btn-success pull-right' %>
</h1>

<div class="row">
<% @product_types.each do |product_type| %>
	<div class="col-sm-3">
		<h2><%= product_type %></h2>
		<ul>
		<%
			@metafields = Metafield.where(:product_type => product_type)
			@metafields.each do |metafield|
		%>
			<li><strong><%= link_to format_key(metafield.key), edit_metafield_path(metafield) %> <% if metafield.description.to_s != '' %><a class="info" title="<%= metafield.description %>"><i class="fa fa-info-circle"></i></a><% end %></strong></li>
			<ul>
			<% metafield.values.each do |value| %>
				<li><%= link_to value.name, edit_value_path(value) %></li>
			<% end %>
				<li><%= link_to 'Add', new_metafield_value_path(metafield), :class => 'text-success' %></li>
			</ul>
		<%
			end
		%>
		</ul>
	</div>
<% end %>
</div>

app/views/metafields/new.html.erb
<h1><a href="/metafields">Metafields</a> | New Metafield</h1>

<div class="row">
	<div class="col-sm-3">
		<%= render 'form' %>
	</div>
</div>

app/views/metafields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product type:</strong>
  <%= @metafield.product_type %>
</p>

<p>
  <strong>Key:</strong>
  <%= @metafield.key %>
</p>

<h2>Values</h2>

<ul>
<% @metafield.values.each do |value| %>
	<li><%= value.name %></li>
<% end %>
	<li><%= link_to 'Add', new_metafield_value_path(@metafield), :class => 'btn btn-xs btn-success' %></li>
</ul>

<%= link_to 'Edit', edit_metafield_path(@metafield) %> |
<%= link_to 'Back', metafields_path %>